// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ3rxq0o4QB0vo5RIdpOknNArGzoJ_pjQ',
    appId: '1:19903019689:web:7b19c658143c6d115307b8',
    messagingSenderId: '19903019689',
    projectId: 'examen2repaso',
    authDomain: 'examen2repaso.firebaseapp.com',
    storageBucket: 'examen2repaso.firebasestorage.app',
    measurementId: 'G-MHYBQX0XVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX3S8OLs_phE3VY2U6C3OnW5WKIhDmNOc',
    appId: '1:19903019689:android:23ce6c6cce24c6a15307b8',
    messagingSenderId: '19903019689',
    projectId: 'examen2repaso',
    storageBucket: 'examen2repaso.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2qyqUsjeAkW1TVDJRA1zSPMRBBMAvH8E',
    appId: '1:19903019689:ios:004164da5766ddb55307b8',
    messagingSenderId: '19903019689',
    projectId: 'examen2repaso',
    storageBucket: 'examen2repaso.firebasestorage.app',
    iosBundleId: 'com.example.apartado4act4',
  );
}
